### ISSUE TITLE
Local 404 not found when accessing the power panel locally

### ISSUE THREAD

**Issue by f00d4tehg0dz** [NathanVaughn/powerpanel-business-docker#16]
Hey There!

Struggling to figure out how to access the power panel dashboard through the local address: http://192.168.x.x:3052/local/    

Using docker image@481

Docker log outputs:
```Starting ppbed```
```Starting ppbwd ```

The error I get is 

```
Type Status Report

Message /local/

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
```

![image](https://user-images.githubusercontent.com/1635526/195642641-c5ce1331-28fd-4023-8aa6-4f988cec012a.png)

**Comment by NathanVaughn** [comment]
I've run into the same problem myself and have not been able to solve it. I personally use version 440, as that's the last one that works for me.

**Comment by f00d4tehg0dz** [comment]
Thank you! I'll close it as 440 works : )
