### ISSUE TITLE
Is there a way to run 2 or 3 of these?

### ISSUE THREAD

**Issue by sgtcoder** [NathanVaughn/powerpanel-business-docker#17]
Is there a way to run 2 or 3 of these?

I know when setting a port map the ports have to be different. Is there a reason why we need inbound port mapped open up for all of these ports? I am running their VM version and that's not needed.

**Comment by NathanVaughn** [comment]
If you're just using the USB connection (like I personally do), you only need to expose port 3052 for the HTTP server. And with Docker, you can map it to any port you like. I don't have a UPS with a network card, so I can't say how important the other ports are.

**Comment by sgtcoder** [comment]
I realized you can also use Nginx or Traefik without even exposing any ports at all.
