### ISSUE TITLE
Behind NGINX Proxy - Can't Login

### ISSUE THREAD

**Issue by war59312** [NathanVaughn/powerpanel-business-docker#19]
Hi,

Trying to get PowerPanel Business working behind nginx proxy.

Sadly, logging in to the login page is failing behind my NGINX Proxy.

"Working behind a reverse proxy since version 450 is a struggle."

Tell me about it.

nginx config:

```
http {

        server {

                listen 3053 ssl http2;
                server_name powerpanel.mydomain.com;

                #Certs from Let's Encrypt
                ssl_certificate "/home/admin/certs/fullchain1.pem";
                ssl_certificate_key "/home/admin/certs/privkey1.pem";

                proxy_set_header Referer $http_referer;
                #proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Real-Port $remote_port;
                proxy_set_header X-Forwarded-Host $host:$remote_port;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-Port $remote_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Ssl on;

                location / {
                        proxy_pass https://powerpanel.mydomain.com:53568;
                        #add_header Host powerpanel.mydomain.com;
                        #add_header 'Access-Control-Allow-Origin' https://powerpanel.mydomain.com:53568;
                        #add_header 'Access-Control-Allow-Origin' *;
                        #add_header 'Access-Control-Allow-Credentials' 'true';
                }
        }
}
```

Notice the commented out lines, they dont help. In fact `proxy_set_header Host $host;` or `proxy_set_header Host $host; powerpanel.mydomain.com` stops the page from loading completely.

I get the expected PowerPanel Business Local Login screen.

However, when I click on "LOG IN" I get:

> You've tried to sign in over 10 times. Try again in one minute.

Error is a bunch of BS of course. If I browse to the normal login page, not behind nginx, I can sign in just fine.

Thanks,

Will

P.S. Looks like minimial config just for login page to show:

```
http {

        server {

                listen 3053 ssl http2;

                ssl_certificate "/home/admin/certs/fullchain1.pem";
                ssl_certificate_key "/home/admin/certs//privkey1.pem";

                location / {
                        proxy_pass https://powerpanel.mydomain.com:53568;
                }
        }
}
```

I do see 403 for `/local/rest/v1/login/verify`

See:

`Referrer Policy: strict-origin-when-cross-origin`

Noticed that Dev Tools Network > Response tab shows "Invalid CORS request" when trying to login.

Edit: Finally figured it out. See post below. Knew it had to do something with "origin".

**Comment by war59312** [comment]
Finally. Figured it out. 🥇 

Must use:

`proxy_set_header 'Origin' '';`

This works:

```
http {

        server {

                listen 3053 ssl http2;

                ssl_certificate "/home/admin/certs/fullchain1.pem";
                ssl_certificate_key "/home/admin/certs/privkey1.pem";

                location / {
                        proxy_pass https://powerpanel.mydomain.com:53568;
                        proxy_set_header 'Origin' '';
                }
        }
}
```

**Comment by NathanVaughn** [comment]
Oh my gosh, thank you so much for this. I was finally able to figure out how to update my personal setup from 440, with Traefik. I'm going to work on updating the README today.

**Comment by war59312** [comment]
You are very welcome, glad it helps :)

**Comment by NathanVaughn** [comment]
Added to README
