### ISSUE TITLE
Any chance to run PPB on a Raspberry Pi (ARM)?

### ISSUE THREAD

**Issue by rbauman70** [NathanVaughn/powerpanel-business-docker#33]
Unfortunately, it's the only Linux system we have available for local UPS monitoring.  Attempting to compose fails with
```
pi@rpi4:~/cyberpower/powerpanel-business-docker $ docker compose up
WARN[0000] /home/pi/cyberpower/powerpanel-business-docker/docker-compose.yml: `version` is obsolete
[+] Running 0/1
 ⠏ app Pulling                                                                                   0.9s
no matching manifest for linux/arm/v8 in the manifest list entries
```

**Comment by NathanVaughn** [comment]
Interesting question. I tried running the download from CyberPower in an ARM Docker image and it fails to install, with a generic "not found" error. 

While it is a Java application, with how CyberPower distributes it as a single self-container .sh file, I think a lot of surgery would be required to get it to work on ARM devices, unfortunately.

**Comment by rbauman70** [comment]
Thanks for checking.  I had hopes too since I saw the JRE but I couldn't parse the packaging script.  First time I'd ever seen that approach.
